// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ48NHC_1A08PKmMuFio6tUG3DpP8RPEs',
    appId: '1:334839247429:web:82cf4b6f399db0c1c9692c',
    messagingSenderId: '334839247429',
    projectId: 'movieappdark',
    authDomain: 'movieappdark.firebaseapp.com',
    storageBucket: 'movieappdark.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0i37VMiOl_ZvHMQFE9s_iWzmL1-Im1dA',
    appId: '1:334839247429:android:021e54c122a029c0c9692c',
    messagingSenderId: '334839247429',
    projectId: 'movieappdark',
    storageBucket: 'movieappdark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-fobz6YdEf3XG4MB7vT72pCunzVUMjU',
    appId: '1:334839247429:ios:fb14bb38d4b12964c9692c',
    messagingSenderId: '334839247429',
    projectId: 'movieappdark',
    storageBucket: 'movieappdark.appspot.com',
    iosClientId: '334839247429-0h3jltfffevfld25dai1bmt6rptqjtr8.apps.googleusercontent.com',
    iosBundleId: 'com.yildirayduran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-fobz6YdEf3XG4MB7vT72pCunzVUMjU',
    appId: '1:334839247429:ios:e002efe6d048811ec9692c',
    messagingSenderId: '334839247429',
    projectId: 'movieappdark',
    storageBucket: 'movieappdark.appspot.com',
    iosClientId: '334839247429-tgeo6o66dcakd4mft0ror9nlifsrb5ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );
}
